### ISSUE TITLE
No suitable constructor

### ISSUE THREAD

**Issue by hybaken** [shadowmanos/non-annotated-jackson-example#2]
Hi,
just tried it, but seems its not working.

I have added it as maven project, using java 8 as its required. Here is the stacktrace.

`Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class Person]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: person.json; line: 1, column: 2]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1106)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3702)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2608)
	at Main.main(Main.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)`

**Comment by shadowmanos** [comment]
You have to pass the **-parameters** argument to javac. Unfortunately, intellij doesn't infer that from the pom.xml. In intellij you can set it at the *Additional command line parameters* field of javac options. Here is an example:

![image](https://cloud.githubusercontent.com/assets/5346908/21159184/1e935d7e-c178-11e6-8c8d-730623242b2f.png)
